databases:
  - name: quizzes
    databaseName: quizzes
    user: quizzes

services:
  - type: web
    name: quizzes
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn quiz.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quizzes
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4