# Generated by Django 5.0.1 on 2024-01-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.CharField(max_length=255),
        ),
    ]
