# Generated by Django 5.0.1 on 2024-01-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_question_alter_questionoption_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
