# Generated by Django 5.0.1 on 2024-01-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_questionoption_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='statkey',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
